"""refactoring tables

Revision ID: 1d802aab99eb
Revises: 
Create Date: 2024-04-30 11:22:50.233125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d802aab99eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_creation_date', sa.DateTime(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('manager_reply_text', sa.String(), nullable=True),
    sa.Column('replied_manager_id', sa.Integer(), nullable=True),
    sa.Column('manager_reply_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['replied_manager_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews_registry')
    op.drop_table('staff')
    # ### end Alembic commands ###
