"""Added department column

Revision ID: 39398f832ba9
Revises: 25e67f21c96d
Create Date: 2024-05-15 00:08:54.102623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39398f832ba9'
down_revision: Union[str, None] = '25e67f21c96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews_registry', sa.Column('department', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews_registry', 'department')
    # ### end Alembic commands ###
